GET http://localhost:8000/api/v1/

### 
GET http://localhost:8000/api/v1/auth/greeting

###
GET http://localhost:8000/api/v1/platforms/greeting

### Sign Up Route
POST http://localhost:8000/api/v1/auth/signup
Content-Type: application/json

{
    "fullName": "Ibirongbe Moses",
    "userName": "moses485",
    "email": "mosesibirongbe@gmail.com",
    "password": "Dynastyda1234#"
}

### Sign In Route
POST http://localhost:8000/api/v1/auth/signin
Content-Type: application/json

{
    "email": "emzzyoluwole@gmail.com",
    "password": "Dynastyda1234#"
}

### Sign Out Route
POST http://localhost:8000/api/v1/auth/signout

### Send Verification Code
PATCH http://localhost:8000/api/v1/auth/send-verification-code
Content-Type: application/json

{
    "email": "mosesibirongbe@gmail.com"
}

### Verify Verification Code 
PATCH http://localhost:8000/api/v1/auth/verify-verification-code
Content-Type: application/json

{
    "email": "emzzyoluwole@gmail.com",
    "providedCode": 272325
}