GET http://localhost:8000/api/v1/

### 
GET http://localhost:8000/api/v1/auth/greeting

###
GET http://localhost:8000/api/v1/platforms/greeting

### Sign Up Route
POST http://localhost:8000/api/v1/signup
Content-Type: application/json

{
    "fullName": "Mojiboye Emmanuel",
    "userName": "dynasty",
    "email": "emzzyoluewole@gmail.com",
    "password": "dynasty1234"
}